"""Add recall_bot_id to meetings

Revision ID: a79ff38af965
Revises: ba249132bcec
Create Date: 2026-03-09 10:43:57.691128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a79ff38af965'
down_revision: Union[str, None] = 'ba249132bcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE summaries CASCADE')
    op.execute('DROP TABLE transcripts CASCADE')
    op.execute('DROP TABLE users CASCADE')
    op.add_column('action_items', sa.Column('text', sa.String(length=1024), nullable=False))
    op.add_column('action_items', sa.Column('assignee_email', sa.String(length=256), nullable=True))
    op.add_column('action_items', sa.Column('priority', sa.String(length=16), nullable=True))
    op.add_column('action_items', sa.Column('completed', sa.Boolean(), nullable=False))
    op.alter_column('action_items', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('action_items', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('action_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('action_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.drop_column('action_items', 'description')
    op.drop_column('action_items', 'assigned_to')
    op.add_column('meetings', sa.Column('recall_bot_id', sa.String(length=128), nullable=True))
    op.alter_column('meetings', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('meetings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('meetings', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('meetings', 'calendar_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('meetings', 'google_event_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('uq_meetings_external_id'), 'meetings', type_='unique')
    op.create_index(op.f('ix_meetings_external_id'), 'meetings', ['external_id'], unique=True)
    op.create_index(op.f('ix_meetings_start_time'), 'meetings', ['start_time'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.drop_column('meetings', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('meetings_created_by_fkey'), 'meetings', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_start_time'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_external_id'), table_name='meetings')
    op.create_unique_constraint(op.f('uq_meetings_external_id'), 'meetings', ['external_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('meetings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('meetings', 'google_event_id',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('meetings', 'calendar_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('meetings', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('meetings', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('meetings', 'title',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('meetings', 'recall_bot_id')
    op.add_column('action_items', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('action_items', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('action_items_assigned_to_fkey'), 'action_items', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.alter_column('action_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('action_items', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('action_items', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('action_items', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('action_items', 'completed')
    op.drop_column('action_items', 'priority')
    op.drop_column('action_items', 'assignee_email')
    op.drop_column('action_items', 'text')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'employee'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transcripts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('transcripts_meeting_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transcripts_pkey'))
    )
    op.create_table('summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('summaries_meeting_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('summaries_pkey'))
    )
    # ### end Alembic commands ###
